Feat/support for new agents
bastionzero/webshell-common-ts pull request #52
Opened 2022-01-12 18:23 UTC by sidpremkumar

## Description of the change

Description here (why is it needed, what does it do)....

## Relevant release note information

Release Notes:

## Related JIRA tickets

Relates to JIRA: CWC-XXX

## Have you considered the security impacts?

Does this PR have any security impact?

- [ ] Yes
- [ ] No

If yes, please explain:

2022-02-04 21:40 UTC, tflpd requested changes

2022-02-04 21:40 UTC, tflpd commented on http/v2/target/types/target.types.ts
> +}
These should be in sep files, every class has its own file

2022-02-07 22:26 UTC, chad-cwc commented on http/v2/target/kube/types/kube-cluster-summary.types.ts
> -export interface KubeClusterSummary {
The old version's `status` was of type `AgentStatus`, and `TargetBase.status` is of type `TargetStatus`. I believe they are effectively the same, but I wanted to point this out in case we need to revert some changes here.

2022-02-10 18:06 UTC, lipmas approved these changes

2022-02-10 18:11 UTC, merged